### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by xMacoy01** [vanhbakaa/Fabrika-Friends-Factory#13]
![image](https://github.com/user-attachments/assets/35a5c82d-0653-4e7b-8dee-1ade622286e5)

**Comment by vanhbakaa** [comment]
Don't use it then

**Comment by vanhbakaa** [comment]
The project relies on several libraries for tasks like handling requests and proxies (aiohttp, cloudscraper), automation (Faker), and encryption (pycryptodome). These libraries, especially when used in combination, might appear suspicious to some antivirus programs, which are sensitive to automated behaviors and web scraping scripts, as they can sometimes be associated with malicious botting or spam activities
