### ISSUE TITLE
New bot make

### ISSUE THREAD

**Issue by AntiWarforever** [vanhbakaa/Fabrika-Friends-Factory#8]
In the previous phase of Rocky Everyone has about half of their tokens left in the game and can't withdraw it, but you can take risks with them in the iq rabbit new game (with low risk, but with a high number, you can earn profit)
Especially for a large number of accounts, some of them may grow a lot with this method. 
Can from nothing received something...
This idea came to me by accident, but I can't make bot

**Comment by vanhbakaa** [comment]
i will check it out

**Comment by AntiWarforever** [comment]
Your problem is that you do not continue projects
I have already suggested to you about making a Rocky rabbit bot(IQ rabbit game) 
And I also said that I have a method that can be grown with a small capital, because we are not taking any risks, we were risking the same money we took from Rocky.
(If the previous candle was red, we will buy long immediately after the next candle)
The input value is low but the number of enter is high (sometimes we receive several times than input)
The price of rocky token has increased too much
![Screenshot_2024-11-12-14-02-45-363_com polestar super clone-edit](https://github.com/user-attachments/assets/8b5c9c17-6a6f-4d3b-b565-c87eca405f19)

**Comment by AntiWarforever** [comment]
I can help you in strategy
But I need to know what information you can get from Rocky, for example, can you extract the color of the candle a few seconds before the last 30 seconds? (the same 30 seconds that can no longer be entered)
